### ISSUE TITLE
the "services" options needs to be a list of strings and/or arrays

### ISSUE THREAD

**Issue by sanketharad** [BorisOsipov/wdio-reportportal-reporter#56] opened 2019-03-04 11:08 UTC
## The problem

Briefly describe the issue you are experiencing or the feature you want) Tell us what you were trying to do and what happened instead.

## Environment

* WebdriverIO version:5.6.3
* wdio-reportportal-version version:0.0.23
* Node.js version:v10.15.1
* WDIO Testrunner and version(mocha\cucumber\jasmine): "mocha": "^6.0.2",
* Additional wdio packages used (if applicable):

## Details

Stderr:
[0-0] 2019-03-04T11:02:42.969Z ERROR @wdio/runner: Error: Type check for option "services" failed: the "services" options needs to be a list of strings and/or arrays
    at validateConfig (/home/sanketharad/Documents/webdriver-test/node_modules/@wdio/config/build/utils.js:125:17)
    at remote (/home/sanketharad/Documents/webdriver-test/node_modules/webdriverio/build/index.js:30:45)
    at initialiseInstance (/home/sanketharad/Documents/webdriver-test/node_modules/@wdio/runner/build/utils.js:84:36)
    at Runner._initSession (/home/sanketharad/Documents/webdriver-test/node_modules/@wdio/runner/build/index.js:202:87)
    at Runner.run (/home/sanketharad/Documents/webdriver-test/node_modules/@wdio/runner/build/index.js:90:32)
    at process._tickCallback (internal/process/next_tick.js:68:7)

Worker Error:
Error: Type check for option "services" failed: the "services" options needs to be a list of strings and/or arrays
    at validateConfig (/home/sanketharad/Documents/webdriver-test/node_modules/@wdio/config/build/utils.js:125:17)
    at remote (/home/sanketharad/Documents/webdriver-test/node_modules/webdriverio/build/index.js:30:45)
    at initialiseInstance (/home/sanketharad/Documents/webdriver-test/node_modules/@wdio/runner/build/utils.js:84:36)
    at Runner._initSession (/home/sanketharad/Documents/webdriver-test/node_modules/@wdio/runner/build/index.js:202:87)
    at Runner.run (/home/sanketharad/Documents/webdriver-test/node_modules/@wdio/runner/build/index.js:90:32)
    at process._tickCallback (internal/process/next_tick.js:68:7)

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

**Comment by BorisOsipov** [comment] 2019-03-04 11:12
Hi @sanketharad `wdio-reportportal-version version:0.0.23` doesn't support wdio v5 yet.

Currently wdio v5 support is in progress. I will appreciate if you use\test https://github.com/BorisOsipov/wdio-rp-tmp and give feedback.
Installation instruction you will find in https://github.com/BorisOsipov/wdio-rp-tmp#installation

**Comment by BorisOsipov** [comment] 2019-03-04 11:12
Duplicate of https://github.com/BorisOsipov/wdio-reportportal-reporter/issues/55

**Closed by BorisOsipov** 2019-03-04 11:12 UTC
